POST https://code.oneki.org:4000/auth/login
Content-Type: application/json

{
	"username": "test",
    "password": "test"
}

###

POST https://qz53v.csb.app//auth/login
Content-Type: application/json

{
	"username": "test",
    "password": "test"
}